/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa.jbudget105053;

import it.unicam.cs.pa.jbudget105053.javafx.JavaFXJBudget;
import javafx.application.Application;

import java.io.IOException;

public class App {
    public static void main(String[] args) throws IOException {
        launchGui();
    }

    private static void launchGui() {
        Application.launch(JavaFXJBudget.class);
    }
}